
// === FLUXO COMPLETO ===
const out = [];
renderSourceFilterTabs();
out.push('tabs tem Justiça USA? ' + document.getElementById("source-filter-tabs").innerHTML.includes("Justiça USA"));
out.push('tabs tem PDFs Variados? ' + document.getElementById("source-filter-tabs").innerHTML.includes("PDFs Variados"));
out.push('tabs tem Redes Sociais? ' + document.getElementById("source-filter-tabs").innerHTML.includes("Redes Sociais"));
out.push('contagem total: ' + document.getElementById("database-total-count").textContent);
const set = (id, v) => { document.getElementById(id).value = v; };
set("as-title", "Livro Teste — A Internacional da Fraude");
set("as-source", "Editora Teste");
set("as-category", "__nova__");
set("as-new-category", "Bibliografia Internacional");
set("as-date", "2026");
set("as-link", "https://exemplo.com/livro");
set("as-summary", "Livro de referência sobre a internacional do crime.");
set("as-transcript", "CAPÍTULO 1 — trechos citáveis do livro teste.");
document.getElementById("as-studio").checked = true;
await saveNewSource(null);
const nova = getAllSources().find(s => s.title.includes("Livro Teste"));
out.push("fonte criada? " + !!nova + " | categoria: " + (nova && nova.category));
out.push("categoria nova registrada? " + (getCategoryRegistry()["cat_bibliografia_internacional"] ? "sim (" + getCategoryRegistry()["cat_bibliografia_internacional"].label + ")" : "NÃO"));
set("ni-title-" + nova.id, "PDF do capítulo 3");
set("ni-link-" + nova.id, "https://exemplo.com/cap3.pdf");
set("ni-note-" + nova.id, "prova do fluxo de dinheiro");
await saveSourceItem(nova.id);
const nova2 = getAllSources().find(s => s.id === nova.id);
out.push("item criado na fonte? " + (nova2.items.length === 1 ? "sim (" + nova2.items[0].title + ")" : "NÃO"));
set("ni-title-yt_cnn_completa", "Trecho 08:43 transcrito");
set("ni-note-yt_cnn_completa", "a frase-mãe do livro");
await saveSourceItem("yt_cnn_completa");
const emb = getAllSources().find(s => s.id === "yt_cnn_completa");
out.push("item na fonte embutida? " + (emb.items.length === 1 ? "sim" : "NÃO"));
const entries = getFontesCustomEntries();
out.push("entries Estúdio: " + entries.length + " → " + entries.map(e => e.kind + ":" + e.label.slice(0, 34)).join(" | "));
out.push("fonte sem upload não tem fileId? " + !getAllSources().find(s => s.id === nova.id).fileId);
out.push("idbSupported() false no stub (guarda OK)? " + (idbSupported() === false));
out.push("fmtSize(2400000) = " + fmtSize(2400000) + " | fmtSize(30000) = " + fmtSize(30000));
// toggle do botão Adicionar Fonte ↔ Voltar ao menu (pedido Miguel) + sem janelinha
toggleAddSourcePanel();
out.push("form aberto: botão virou Voltar? " + (document.getElementById("btn-add-source-label").textContent.includes("Voltar ao menu")));
out.push("form aberto: lista escondida (sem janelinha)? " + document.getElementById("source-grid-wrapper").classList.contains("hidden"));
out.push("form aberto: filtros escondidos? " + document.getElementById("database-modal-filters").classList.contains("hidden"));
toggleAddSourcePanel();
out.push("form fechado: botão voltou p/ Adicionar? " + (document.getElementById("btn-add-source-label").textContent.includes("Adicionar Fonte")));
out.push("form fechado: lista de volta? " + !document.getElementById("source-grid-wrapper").classList.contains("hidden"));
// auditoria de links YouTube
const brokenCount = sourcesDatabase.filter(s => s.broken).length;
out.push("links marcados indisponíveis: " + brokenCount + " (esperado 13)");
out.push("Tucker com link real? " + (sourcesDatabase.find(s => s.id === "yt_paulo_figueiredo_tucker").link.includes("fRXhn0UN-_4")));
out.push("Fox/Lou Dobbs com link real? " + (sourcesDatabase.find(s => s.id === "yt_eduardo_fox_news").link.includes("mTziWNvuOco")));
out.push("Monark corte com link real? " + (sourcesDatabase.find(s => s.id === "yt_eduardo_podcast_monark").link.includes("-rvebyRe7QY")));
entries.forEach(e => customCheckboxes.push({ checked: true, getAttribute: () => e.id }));
document.getElementById("chk-consult-canonical-memory").checked = true;
const sel = getSelectedFontesParts();
out.push("custom no prompt: " + sel.custom.length + " itens; fonte tem fichamento? " + sel.custom.some(c => c.text.includes("Fichamento")));
out.push("item anexo entra no prompt? " + sel.custom.some(c => c.text.includes("prova do fluxo de dinheiro")));
deleteSourceItem(nova.id, nova2.items[0].id);
out.push("item apagado? " + (getAllSources().find(s => s.id === nova.id).items.length === 0));
confirmDeleteSource(nova.id);
out.push("fonte custom apagada? " + !getAllSources().find(s => s.id === nova.id));
confirmDeleteSource("yt_cnn_completa");
out.push("embutida oculta? " + !getAllSources().find(s => s.id === "yt_cnn_completa"));
restoreHiddenSources();
out.push("embutida restaurada? " + !!getAllSources().find(s => s.id === "yt_cnn_completa"));
out.push("persistiu custom sources? " + (__store["miguel_fontes_custom_v2"] !== undefined));
out.push("persistiu categorias novas? " + (__store["miguel_fontes_custom_cats_v1"] || "").includes("Bibliografia Internacional"));
out.push("persistiu itens overlay? " + (__store["miguel_fontes_items_v1"] || "").includes("Trecho 08:43"));
return out.join("\n");
